export const projects = {
  html: "<h1>  Combate CB5  </h1>  <h3>CB5 is the fifth version of an on-board computer device designed to be used on the mechanized poison dispensers from the company <a href='http://combatesf.com.br'>Combate Serviços Florestais</a>. This device communicates via bluetooth with an android device. It provides GPS information to further processing and the possibility of applying doses of poison as required. This project was built using C++ and the Arduino Software.</h3>",
  html2: "<h1>  Portifolio  </h1>  <a href='https://github.com/'>portifolio</a> <h3>This was my first React application. That's how I started my front-end knowledge. This is an ongoing project and I still have brand new ideas to build here. While doing this project I learned what I should or shouldn’t do while developing front-end projects and that’s why this code is not the best example of a well-built front-end.</h3>",
  html3: "<h1> Web Feedback Widget </h1>  <a href='https://github.com/'>FeeDget</a> <h3>This project was built during a programming event using React and Tailwind CSS. The purpose of this project is a web feedback widget and it was built together with the FeedGetMobile App. </h3>",
  html4: "<h1> Combate App</h1>  <a href='https://github.com/'>combate-app</a> <h3>This is an ongoing project. It’s a React Native App being built for a company called Combat Serviços Florestais. This App is part of a machine that makes the application of ant killer inside eucalyptus crops. This app will communicate with an external Bluetooth device to get precise GPS information and request poison applications. This project works in parallel with combate-cb5.</h3>",
  html5: "<h1> Mobile Feedback Widget</h1>  <a href='https://github.com/'>FeeDgetMobile</a> <h3>This project was built during a programming event using React Native. The propose of this project is a mobile feedback widget and it was built together with the Feedget Web App.</h3>",
  html6: "<h1>Smart Screen</h1>  <a href='https://github.com/'>smart-screen</a> <h3>This was my first React Native App. The purpose of this app is to control my D.I.Y home automation. This was built to be minimalistic. It has access to my calendar and the weather forecast.</h3>",
  html7: "<h1>Feedback Widget Server</h1>  <a href='https://github.com/'>FeeDgetServer</a> <h3>This project is the back-end API to the FeeDget and FeedGetMobile applications. This API is responsible for sending feedback e-mails and database management.</h3>",
};
